import calliope
import os

#File-naming function for standard models generated by constructor
def filenamer(params, scenario, type):
    filename=f"{scenario}_{params['horizon_start'][:4]}_{params['horizon_end'][:4]}_{params['output_model_name']}.{type}"
    return filename

#constructor for standard model
def standardised_model_config(params):

    #auto-config paths and directories
        # path_output_directory = os.path(f"../../results/{params['output_directory_name']}")
        # path_output_netcdf = os.path(f"../../results/{params['output_directory_name']}/{params['output_model_name']}.netcdf")
        path_model_config_yaml = os.path.normpath(f"SoC_proxy_TSA/model_config/{params['config_yaml_name']}.yaml")

    #auto-config calliope logging
        
        calliope.set_log_verbosity("ERROR", include_solver_output=params['calliope_full_log'][0])

    #auto-config overrides for calliope config

    #initialise dictionary
        calliope_override_dictionary={}
    
    #define horizons
        if 'horizon_start' in params and 'horizon_start' in params:
            calliope_override_dictionary['config.init.subset.timesteps'] = [params['horizon_start'],params['horizon_end']]
    
    #define tvp source
        if 'filename_time_varying_parameters' in params:
            calliope_override_dictionary['data_tables.time_varying_parameters.data'] = f"../data_tables/full_horizon/{params['filename_time_varying_parameters']}.csv"
    
    #provide option for custom override parameters
        if 'dict_additional_overrides' in params:
            calliope_override_dictionary.update(params['dict_additional_overrides'])

    #auto-config calliope model
        model = calliope.read_yaml(
            path_model_config_yaml,
            scenario=params['scenario_name'] if 'scenario_name' in params else 'standard',
            override_dict=calliope_override_dictionary

        )

        #determine filename based on scenario
        filename = f"standard_{params['horizon_start'][:4]}_{params['horizon_end'][:4]}_reference.nc"
    
   #export configured calliope model
        return model, filename

#constructor for clustered model
def clustered_model_config(params):

    #auto-config paths and directories
        # path_output_directory = os.path(f"../../results/{params['output_directory_name']}")
        # path_output_netcdf = os.path(f"../../results/{params['output_directory_name']}/{params['output_model_name']}.netcdf")
        path_model_config_yaml = os.path.normpath(f"SoC_proxy_TSA/model_config/{params['config_yaml_name']}.yaml")

    #auto-config calliope logging
        calliope.set_log_verbosity("ERROR", include_solver_output=params['calliope_full_log'][0])

    #check clustering input has been included and is a csv
        if 'path_cluster_map' in params:
             if not params['path_cluster_map'].endswith('.csv'):
                raise Exception('The path_to_cluster_csv variable is not a csv.')
        else:     
             raise Exception('The path_to_cluster_csv variable is not set within the params dictionary.')


    #initialise dictionary
        calliope_override_dictionary={}
    
    #define horizons
        if 'horizon_start' in params and 'horizon_start' in params:
            calliope_override_dictionary['config.init.subset.timesteps'] = [params['horizon_start'],params['horizon_end']]
    
    #define tvp source
        if 'path_timeseries' in params and params['path_timeseries']:
            calliope_override_dictionary['data_tables.time_varying_parameters.data'] = f"../../{params['path_timeseries']}"
        elif 'filename_time_varying_parameters' in params:
            raise Exception('No timeseries provided.')
    
    #provide option for custom override parameters
        if 'dict_additional_overrides' in params:
            calliope_override_dictionary.update(params['dict_additional_overrides'])

    #add inter-storage-cluster-math functions because clustering has been applied and we need to preserve SoC values
        add_math_paths_config = {'maths_cyclic_constraints': "../custom_mathematics/add_maths_cycle_constraints.yaml"}
        extra_math_config = ['maths_cyclic_constraints','storage_inter_cluster']
        calliope_override_dictionary['config.init.math_paths'] = add_math_paths_config
        calliope_override_dictionary['config.init.extra_math'] = extra_math_config

    #add time clustering data table
        CLUSTER_PARAM = 'PeriodNum'
        path_cluster_map = f"../../{params['path_cluster_map']}"
        calliope_override_dictionary['data_tables.cluster_days'] = {
             'data': path_cluster_map,
             'rows': 'timesteps',
             "add_dims": {"parameters": CLUSTER_PARAM}
        }


    #auto-config calliope model
        model = calliope.read_yaml(
            file=path_model_config_yaml,
            scenario=params['scenario_name'] if 'scenario_name' in params else 'standard',
            time_cluster=CLUSTER_PARAM,
            override_dict=calliope_override_dictionary
        )

        #can add maths instantaneously via calliope.from_yaml(..., math_dict={"my_new_math_1": {...}, ...})
    
   #export configured calliope model
        return model

def reconstructured_full_model_config(params):
     
    #auto-config paths and directories
        # path_output_directory = os.path(f"../../results/{params['output_directory_name']}")
        # path_output_netcdf = os.path(f"../../results/{params['output_directory_name']}/{params['output_model_name']}.netcdf")
        path_model_config_yaml = os.path.normpath(f"SoC_proxy_TSA/model_config/{params['config_yaml_name']}.yaml")

    #auto-config calliope logging
        calliope.set_log_verbosity("ERROR", include_solver_output=params['calliope_full_log'][0])

    #initialise dictionary
        calliope_override_dictionary={}
    
    #define horizons
        if 'horizon_start' in params and 'horizon_start' in params:
            calliope_override_dictionary['config.init.time_subset'] = [params['horizon_start'],params['horizon_end']]
    
    #define tvp source
        if 'path_to_new_timeseries' in params and params['path_to_new_timeseries']:
             calliope_override_dictionary['data_tables.time_varying_parameters.data'] = f"../../{params['path_to_new_timeseries']}"
        elif 'filename_time_varying_parameters' in params:
            raise Exception('No new timeseries provided.')
            # calliope_override_dictionary['data_tables.time_varying_parameters.data'] = f"../data_tables/{params['filename_time_varying_parameters']}.csv"

    
    #provide option for custom override parameters
        if 'dict_additional_overrides' in params:
            calliope_override_dictionary.update(params['dict_additional_overrides'])

    #add inter-storage-cluster-math functions because clustering has been applied and we need to preserve SoC values
        add_math_config = ["../custom_mathematics/add_maths_cycle_constraints.yaml"]
        calliope_override_dictionary['config.build.add_math'] = add_math_config

    #auto-config calliope model
        model = calliope.Model(
            path_model_config_yaml,
            scenario=params['scenario_name'] if 'scenario_name' in params else 'standard',
            override_dict=calliope_override_dictionary

        )

        #determine filename based on scenario
        # filename = filenamer(params, 'clustered','netcdf')
    
   #export configured calliope model
        return model