defaults:
  dispatch_mode: tsa

  data_params:
    country: NL
    start_date: 2010-01-01
    end_date: 2020-01-01

  soc_proxy_params:
    renewables_fields_and_weights:
      solar: 2
      onshore_wind: 1
      offshore_wind: 1

    soc_decomposition:
      method: fft_lowpass
      time_horizon_hours: 24

    margin_mode: fixed
    margin_value: 0.04

  tsa_params:
    k_periods: 30
    period_duration: 1D
    preserve_column_means: true

    soc_proxy:
      enabled: true
      lambda_soc: 0.5
      proxy_field_name: surplus_LDES

    cluster:
      method: kmedoids
      random_state: 42

    representation:
      method: medoid

  calliope_params:
    scenario: standard

  solver_params:
    solver: gurobi

  output_params:
    save_capacities: true
    save_costs: true
    save_metrics: true


experiments:

  smoke_no_proxy:
    data_params:
      start_date: 2010-01-01
      end_date: 2010-03-01

    tsa_params:
      k_periods: 5

      soc_proxy:
        enabled: false

      cluster:
        method: kmeans

      representation:
        method: medoid

  smoke_proxy:
    data_params:
      start_date: 2010-01-01
      end_date: 2010-03-01

    tsa_params:
      k_periods: 5

      soc_proxy:
        enabled: true
        lambda_soc: 0.5

      cluster:
        method: kmeans

      representation:
        method: medoid