"""Plot SoC Proxy smoothing-sensitivity outcomes."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D


# ---------------------------------------------------------------------------
# Plot conventions
# ---------------------------------------------------------------------------

METHOD_LABELS = {
    "fft_lowpass": "FFT low-pass",
    "gaussian": "Gaussian",
    "moving_average": "Moving average",
}

# Multiplicative offsets on the log-scaled x-axis.
#
# Slightly wider than for point plotting so the box-and-whisker
# distributions remain visually distinct.
METHOD_LOG10_OFFSETS = {
    "fft_lowpass": -0.07,
    "gaussian": 0.0,
    "moving_average": 0.07,
}

# Box width as a fraction of its x position. Because the x-axis is
# logarithmic, scaling width with position gives visually similar widths
# across the full horizon range.
BOX_WIDTH_FRACTION = 0.10


# ---------------------------------------------------------------------------
# Public plotter
# ---------------------------------------------------------------------------


def plot_smoothing_sensitivity(
    *,
    manifest_path: str | Path = ("results/sensitivity_smoothing_manifest.parquet"),
    results_dir: str | Path = "results",
    output_path: str | Path | None = None,
    connect_medians: bool = True,
):
    """Plot CEM error metrics across smoothing methods and timescales.

    Visual encoding
    ---------------
    x
        ``time_horizon_hours`` on a logarithmic axis.
    colour
        SoC Proxy smoothing method.
    marker
        Country.
    fill
        Five-year cases are hollow; ten-year cases are filled.

    Parameters
    ----------
    manifest_path
        Sweep manifest generated by the smoothing-sensitivity runner.
    results_dir
        Directory containing consolidated result Parquets.
    output_path
        Optional path at which to save the figure.
    show_median
        If True, draw the median response for each smoothing method across
        all countries and weather horizons.

    Returns
    -------
    tuple
        ``(fig, axes)``
    """

    manifest_path = Path(manifest_path)

    results_dir = Path(results_dir)

    manifest = pd.read_parquet(manifest_path)

    parameters = pd.read_parquet(results_dir / "parameters.parquet")

    investment_metrics = pd.read_parquet(results_dir / "investment_metrics.parquet")

    signal_metrics = pd.read_parquet(results_dir / "signal_metrics.parquet")

    data = _build_plot_data(
        manifest=manifest,
        parameters=parameters,
        investment_metrics=investment_metrics,
        signal_metrics=signal_metrics,
    )

    methods = [
        method
        for method in METHOD_LABELS
        if method in set(data["decomposition_method"])
    ]

    if not methods:
        raise RuntimeError(
            "No recognised smoothing methods were found in the sweep manifest."
        )

    # Sample decomposition-method colours from the Plasma colormap.
    cmap = plt.get_cmap("plasma")

    method_colours = {
        method: cmap(value)
        for method, value in zip(
            methods,
            np.linspace(
                0.1,
                0.9,
                len(methods),
            ),
            strict=True,
        )
    }

    panels = [
        (
            "LDES capacity error",
            "ldes_capacity_error",
            "LDES capacity error (%)",
            True,
        ),
        (
            "SoC Proxy Delta Error (reference)",
            "soc_proxy_nrmse",
            "nRMSE (%)",
            True,
        ),
        (
            "CAPEX-weighted MACME",
            "weighted_macme",
            "Weighted MACME (%)",
            False,
        ),
        (
            "SoC Delta Error",
            "soc_nrmse",
            "nRMSE (%)",
            False,
        ),
    ]

    fig, axes = plt.subplots(
        2,
        2,
        figsize=(13.5, 8.5),
        layout="constrained",
        squeeze=False,
    )

    horizons = sorted(data["time_horizon_hours"].unique())

    for ax, (
        title,
        column,
        ylabel,
        zero_line,
    ) in zip(
        axes.flat,
        panels,
        strict=True,
    ):
        _plot_panel(
            ax,
            data=data,
            value_column=column,
            methods=methods,
            method_colours=method_colours,
            connect_medians=connect_medians,
        )

        ax.set_title(title)

        ax.set_ylabel(ylabel)

        ax.set_xlabel("Smoothing timescale (hours)")

        ax.set_xscale("log")

        ax.set_xticks(horizons)

        ax.set_xticklabels([_format_horizon(horizon) for horizon in horizons])

        ax.grid(
            axis="y",
            alpha=0.25,
        )

        if zero_line:
            ax.axhline(
                0,
                linewidth=1,
                linestyle="--",
                alpha=0.7,
            )

    _add_figure_legend(
        fig,
        methods=methods,
        method_colours=method_colours,
    )

    if output_path is not None:
        output_path = Path(output_path)

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        fig.savefig(
            output_path,
            dpi=200,
            bbox_inches="tight",
        )

    return fig, axes


# ---------------------------------------------------------------------------
# Panel plotting
# ---------------------------------------------------------------------------


def _plot_panel(
    ax,
    *,
    data: pd.DataFrame,
    value_column: str,
    methods: list[str],
    method_colours: dict[str, str],
    connect_medians: bool,
) -> None:
    """Plot method-wise box-and-whisker distributions by smoothing horizon.

    Each box pools all case-study observations available for one
    decomposition method and smoothing horizon.

    Boxes show the interquartile range, centre lines show the median,
    and whiskers extend to the most extreme observations within
    1.5 times the IQR. More extreme observations are not displayed.
    """

    for method in methods:
        method_data = data.loc[data["decomposition_method"] == method]

        colour = method_colours[method]

        x_factor = 10 ** (
            METHOD_LOG10_OFFSETS.get(
                method,
                0.0,
            )
        )

        positions: list[float] = []
        distributions: list[np.ndarray] = []
        medians: list[float] = []

        for horizon, subset in method_data.groupby(
            "time_horizon_hours",
            sort=True,
        ):
            values = subset[value_column].dropna().to_numpy(dtype=float)

            if len(values) == 0:
                continue

            position = float(horizon) * x_factor

            positions.append(position)

            distributions.append(values)

            medians.append(float(np.median(values)))

        if not distributions:
            continue

        widths = [position * BOX_WIDTH_FRACTION for position in positions]

        ax.boxplot(
            distributions,
            positions=positions,
            widths=widths,
            whis=1.5,
            showfliers=True,
            patch_artist=True,
            manage_ticks=False,
            boxprops={
                "facecolor": colour,
                "edgecolor": colour,
                "alpha": 0.22,
                "linewidth": 1.3,
            },
            whiskerprops={
                "color": colour,
                "linewidth": 1.2,
            },
            capprops={
                "color": colour,
                "linewidth": 1.2,
            },
            medianprops={
                "color": colour,
                "linewidth": 2.2,
            },
        )

        # Connecting medians makes the response to smoothing timescale
        # easier to follow without plotting the underlying observations.
        if connect_medians:
            ax.plot(
                positions,
                medians,
                color=colour,
                linewidth=1.3,
                marker="o",
                markersize=3.5,
                zorder=4,
            )


# ---------------------------------------------------------------------------
# Result extraction
# ---------------------------------------------------------------------------


def _build_plot_data(
    *,
    manifest: pd.DataFrame,
    parameters: pd.DataFrame,
    investment_metrics: pd.DataFrame,
    signal_metrics: pd.DataFrame,
) -> pd.DataFrame:
    """Combine sweep dimensions and the four plotted metrics."""

    required_manifest_columns = {
        "case_id",
        "experiment_name",
        "country",
        "start_year",
        "end_year",
        "duration_years",
        "decomposition_method",
        "time_horizon_hours",
        "k_periods",
    }

    missing = required_manifest_columns - set(manifest.columns)

    if missing:
        raise KeyError(f"Sensitivity manifest is missing columns: {sorted(missing)}")

    data = manifest.loc[
        :,
        [
            "case_id",
            "experiment_name",
            "country",
            "start_year",
            "end_year",
            "duration_years",
            "decomposition_method",
            "time_horizon_hours",
            "k_periods",
        ],
    ].copy()

    data = data.loc[data["duration_years"] == 10].copy()

    # Confirm that every case represented in the manifest is present in
    # consolidated parameters. This catches a forgotten consolidation step.
    known_case_ids = set(parameters["case_id"])

    missing_parameters = [
        case_id for case_id in data["case_id"] if case_id not in known_case_ids
    ]

    if missing_parameters:
        raise RuntimeError(
            "Some sweep cases are absent from consolidated "
            "parameters.parquet. Run consolidate_results() first. "
            f"Missing case IDs: {missing_parameters}"
        )

    # -------------------------------------------------------------------
    # CEM investment metrics
    # -------------------------------------------------------------------

    metric_columns = {
        "ldes_capacity_error_signed": ("ldes_capacity_error"),
        "macme_capex_weighted_annualised": ("weighted_macme"),
    }

    for metric_name, column_name in metric_columns.items():
        values = _investment_metric(
            investment_metrics,
            case_ids=data["case_id"].tolist(),
            metric=metric_name,
        )

        data[column_name] = data["case_id"].map(values) * 100.0

    # -------------------------------------------------------------------
    # Clustered-v-reference SoC error
    # -------------------------------------------------------------------

    soc_values = _signal_metric(
        signal_metrics,
        case_ids=data["case_id"].tolist(),
        error_family="cem",
        signal_type="delta",
        metric="nrmse",
        normalisation_basis=("reference_proxy_full_range"),
        window_half_width_days=None,
    )

    soc_proxy_values = _signal_metric(
        signal_metrics,
        case_ids=data["case_id"].tolist(),
        error_family="reference_approximation",
        signal_type="delta",
        metric="nrmse",
        normalisation_basis=("comparison_reference_full_range"),
        window_half_width_days=None,
    )

    data["soc_nrmse"] = data["case_id"].map(soc_values) * 100.0

    data["soc_proxy_nrmse"] = data["case_id"].map(soc_proxy_values) * 100.0

    return data


def _investment_metric(
    metrics: pd.DataFrame,
    *,
    case_ids: list[str],
    metric: str,
) -> dict[str, float]:
    """Return one investment metric for every requested case."""

    selected = metrics.loc[
        metrics["case_id"].isin(case_ids) & (metrics["metric"] == metric),
        [
            "case_id",
            "value",
        ],
    ]

    return _to_case_values(
        selected,
        case_ids,
        description=metric,
    )


def _signal_metric(
    metrics: pd.DataFrame,
    *,
    case_ids: list[str],
    error_family: str,
    signal_type: str,
    metric: str,
    normalisation_basis: str | None,
    window_half_width_days: int | None,
) -> dict[str, float]:
    """Return one precisely defined signal metric for every case."""

    mask = (
        metrics["case_id"].isin(case_ids)
        & (metrics["error_family"] == error_family)
        & (metrics["signal_type"] == signal_type)
        & (metrics["metric"] == metric)
    )

    if normalisation_basis is None:
        mask &= metrics["normalisation_basis"].isna()
    else:
        mask &= metrics["normalisation_basis"] == normalisation_basis

    if window_half_width_days is None:
        mask &= metrics["window_half_width_days"].isna()
    else:
        mask &= metrics["window_half_width_days"] == window_half_width_days

    selected = metrics.loc[
        mask,
        [
            "case_id",
            "value",
        ],
    ]

    description = (
        f"{error_family} / "
        f"{signal_type} / "
        f"{metric} / "
        f"{normalisation_basis} / "
        f"window={window_half_width_days}"
    )

    return _to_case_values(
        selected,
        case_ids,
        description=description,
    )


def _to_case_values(
    selected: pd.DataFrame,
    case_ids: list[str],
    *,
    description: str,
) -> dict[str, float]:
    """Validate exactly one metric value per requested case."""

    counts = selected.groupby("case_id").size()

    duplicates = counts[counts > 1]

    if not duplicates.empty:
        raise RuntimeError(
            f"Metric {description!r} produced multiple "
            "rows for cases: "
            f"{duplicates.index.tolist()}"
        )

    values = selected.set_index("case_id")["value"].to_dict()

    missing = [case_id for case_id in case_ids if case_id not in values]

    if missing:
        raise KeyError(f"Metric {description!r} is unavailable for case IDs: {missing}")

    return values


# ---------------------------------------------------------------------------
# Labels / legend
# ---------------------------------------------------------------------------


def _format_horizon(
    hours: float,
) -> str:
    """Format one smoothing-timescale tick."""

    hours = int(hours)

    if hours >= 24 * 30:
        return f"{hours}h\n({hours / (24 * 30):.0f}mo)"

    if hours >= 24 * 7:
        return f"{hours}h\n({hours / (24 * 7):.0f}wk)"

    if hours >= 24:
        return f"{hours}h\n({hours / 24:.0f}d)"

    return f"{hours}h"


def _add_figure_legend(
    fig,
    *,
    methods: list[str],
    method_colours: dict[str, str],
) -> None:
    """Add a decomposition-method legend."""

    handles: list[Line2D] = []

    for method in methods:
        colour = method_colours[method]

        handles.append(
            Line2D(
                [0],
                [0],
                color=colour,
                linewidth=1.5,
                marker="s",
                markersize=8,
                markerfacecolor=colour,
                alpha=0.8,
                label=METHOD_LABELS[method],
            )
        )

    fig.legend(
        handles=handles,
        loc="upper center",
        bbox_to_anchor=(
            0.5,
            1.025,
        ),
        ncol=len(handles),
        frameon=False,
    )
